"""initial schema

Revision ID: 5ebcdb9853bd
Revises: 
Create Date: 2026-04-09 23:37:31.669185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ebcdb9853bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constructs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene_name', sa.String(length=255), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('construct_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['construct_id'], ['constructs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequences')
    op.drop_table('constructs')
    # ### end Alembic commands ###
