"""add index on sequence gene name

Revision ID: d9e332625d1c
Revises: 5ebcdb9853bd
Create Date: 2026-04-10 16:31:06.743882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e332625d1c'
down_revision: Union[str, Sequence[str], None] = '5ebcdb9853bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sequences_gene_name'), 'sequences', ['gene_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sequences_gene_name'), table_name='sequences')
    # ### end Alembic commands ###
